[tool.poetry]
name = "egauge-async"
version = "0.1.0"
description = "Async client for eGauge energy monitor (https://www.egauge.net)"
license = "GPL-3.0-only"
authors = ["Nic Eggert <nic@eggert.io>"]
readme = "README.md"
homepage = "https://github.com/neggert/egauge-async"

[tool.poetry.dependencies]
python = "^3.7"
httpx = ">=0.16.0,<0.19.0"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
pytest = "^6.1.1"
black = "^20.8b1"
flake8 = "^3.8.4"
rope = "^0.18.0"
pytest-asyncio = "^0.14.0"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
